[package]
name = "pinetime-bsp"
version = "0.1.0"
edition = "2024"

[dependencies]
bma425 = { path = "../bma425-rs", features = ["defmt"] }
cst816s-async = { version = "0.1.0", features = ["defmt"] }
defmt = { version = "1.0.1", optional = true }
embassy-embedded-hal = "0.5.0"
embassy-nrf = { version = "0.9.0", features = [
    "gpiote",
    "nfc-pins-as-gpio",
    "nrf52832",
    "time-driver-rtc1",
    "time",
] }
embassy-sync = "0.7.2"
embassy-time = "0.5.0"
embedded-graphics = { version = "0.8.1", features = ["defmt"] }
embedded-hal-async = { version = "1.0.0", features = ["defmt-03"] }
embedded-layout = "0.4.2"
lcd-async = "0.1.1"
nrf-sdc = { version = "0.4.0", features = ["peripheral", "nrf52832", "defmt"] }
static_cell = "2.1.1"

[features]
defmt = [ "dep:defmt", "bma425/defmt", "cst816s-async/defmt", "embedded-graphics/defmt", "embedded-hal-async/defmt-03", "nrf-sdc/defmt"]

[patch.crates-io]
lcd-async = { git = "https://github.com/okhsunrog/lcd-async.git", rev = "50efe0a30a4c68a1502049556b2ffb27c13b9539" }
nrf-sdc = { git = "https://github.com/alexmoon/nrf-sdc.git", rev = "8ac007cbd4556e1123bee2479d66272ddf355844" }
